- name: Remove current dotfiles directory
  become: true
  file:
    path: "~/dotfiles"
    state: absent
- name: Ensure the dotfiles directory exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/dotfiles"
    state: directory
    mode: "0755"
# - name: add github to known-hosts
#   ansible.builtin.known_hosts:
#     name: github.com
#     key: github.com
- name: clone dotfiles repo
  ansible.builtin.git:
    repo: git@github.com:RolandSobczak/dotfiles.git
    key_file: "{{ lookup('env', 'HOME') }}/.ssh/github"
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    clone: yes
    update: yes
- name: clone powerlevel10k
  ansible.builtin.git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/powerlevel10k"
    clone: yes
    update: yes
- name: Remove zshrc
  become: true
  file:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    state: absent
    force: true
- name: Remove profile
  become: true
  file:
    path: "{{ lookup('env', 'HOME') }}/.profile"
    state: absent
    force: true
- name: stow dotfiles
  shell: "cd {{ lookup('env', 'HOME') }}/dotfiles && stow ."
